-- MySQL Script generated by MySQL Workbench
-- 05/12/14 16:26:15
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Client` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `idClient` INT NOT NULL,
  `NumeClient` VARCHAR(45) NOT NULL,
  `PrenumeClient` VARCHAR(45) NOT NULL,
  `AdresaClient` VARCHAR(45) NULL,
  `OrasClient` VARCHAR(45) NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BonInchiriere`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BonInchiriere` ;

CREATE TABLE IF NOT EXISTS `mydb`.`BonInchiriere` (
  `idBonInchiriere` INT NOT NULL,
  `DataBonInchiriere` DATETIME NOT NULL,
  `NrDVDInchiriate` INT NULL,
  `Client_IDClient` INT NOT NULL,
  PRIMARY KEY (`idBonInchiriere`),
  INDEX `fk_BonInchiriere_Client_idx` (`Client_IDClient` ASC),
  CONSTRAINT `fk_BonInchiriere_Client`
    FOREIGN KEY (`Client_IDClient`)
    REFERENCES `mydb`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DVD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DVD` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DVD` (
  `idDVD` INT NOT NULL,
  `TitluFilm` VARCHAR(45) NOT NULL,
  `DescriereFilm` VARCHAR(45) NULL,
  `TarifZilnic` INT NOT NULL,
  `DuarataFilm(min)` INT NULL,
  `NrExemplare` INT NULL,
  PRIMARY KEY (`idDVD`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DVD_has_Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DVD_has_Client` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DVD_has_Client` (
  `DVD_idDVD` INT NOT NULL,
  `Client_idClient` INT NOT NULL,
  PRIMARY KEY (`DVD_idDVD`, `Client_idClient`),
  INDEX `fk_DVD_has_Client_Client1_idx` (`Client_idClient` ASC),
  INDEX `fk_DVD_has_Client_DVD1_idx` (`DVD_idDVD` ASC),
  CONSTRAINT `fk_DVD_has_Client_DVD1`
    FOREIGN KEY (`DVD_idDVD`)
    REFERENCES `mydb`.`DVD` (`idDVD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DVD_has_Client_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `mydb`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CategorieFilm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CategorieFilm` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CategorieFilm` (
  `idCategorieFilm` INT NOT NULL,
  `DenumireCategorie` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategorieFilm`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DVD_has_CategorieFilm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DVD_has_CategorieFilm` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DVD_has_CategorieFilm` (
  `DVD_idDVD` INT NOT NULL,
  `CategorieFilm_idCategorieFilm` INT NOT NULL,
  PRIMARY KEY (`DVD_idDVD`, `CategorieFilm_idCategorieFilm`),
  INDEX `fk_DVD_has_CategorieFilm_CategorieFilm1_idx` (`CategorieFilm_idCategorieFilm` ASC),
  INDEX `fk_DVD_has_CategorieFilm_DVD1_idx` (`DVD_idDVD` ASC),
  CONSTRAINT `fk_DVD_has_CategorieFilm_DVD1`
    FOREIGN KEY (`DVD_idDVD`)
    REFERENCES `mydb`.`DVD` (`idDVD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DVD_has_CategorieFilm_CategorieFilm1`
    FOREIGN KEY (`CategorieFilm_idCategorieFilm`)
    REFERENCES `mydb`.`CategorieFilm` (`idCategorieFilm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BonInchiriere_has_DVD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BonInchiriere_has_DVD` ;

CREATE TABLE IF NOT EXISTS `mydb`.`BonInchiriere_has_DVD` (
  `BonInchiriere_idBonInchiriere` INT NOT NULL,
  `DVD_idDVD` INT NOT NULL,
  PRIMARY KEY (`BonInchiriere_idBonInchiriere`, `DVD_idDVD`),
  INDEX `fk_BonInchiriere_has_DVD_DVD1_idx` (`DVD_idDVD` ASC),
  INDEX `fk_BonInchiriere_has_DVD_BonInchiriere1_idx` (`BonInchiriere_idBonInchiriere` ASC),
  CONSTRAINT `fk_BonInchiriere_has_DVD_BonInchiriere1`
    FOREIGN KEY (`BonInchiriere_idBonInchiriere`)
    REFERENCES `mydb`.`BonInchiriere` (`idBonInchiriere`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BonInchiriere_has_DVD_DVD1`
    FOREIGN KEY (`DVD_idDVD`)
    REFERENCES `mydb`.`DVD` (`idDVD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
