-- MySQL Script generated by MySQL Workbench
-- 05/12/14 16:34:34
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Departament`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Departament` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Departament` (
  `idDepartament` INT NOT NULL,
  `DenumireDepartament` VARCHAR(45) NULL,
  PRIMARY KEY (`idDepartament`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Salariat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Salariat` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Salariat` (
  `idSalariat` INT NOT NULL,
  `NumeSalariat` VARCHAR(45) NOT NULL,
  `DataNstere` DATE NULL,
  `Salariu` FLOAT NULL,
  `Departament_idDepartament` INT NOT NULL,
  PRIMARY KEY (`idSalariat`, `Departament_idDepartament`),
  INDEX `fk_Salariat_Departament_idx` (`Departament_idDepartament` ASC),
  CONSTRAINT `fk_Salariat_Departament`
    FOREIGN KEY (`Departament_idDepartament`)
    REFERENCES `mydb`.`Departament` (`idDepartament`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
